### ISSUE TITLE
CP is inaccessible if the underlying fields aren't present

### ISSUE THREAD

**Issue by Emkaytoo** [verbb/many-to-many#12]
I was testing out the plugin so I created some dummy fields. I happened to name the fields in a way that the many-to-many field was last in the CP. When I deleted the other fields, the many-to-many ceased to work (as expected), but also was unable to be deleted. 

Upon refreshing the page, I got a runtime error and was unable to access the CP, even at the highest level of the CP (`/admin`) that. I have since restored a backed up database, but the error was something like `class manytomanyfield failed`. 

In this environment it was fine, but a check for that would be helpful, as would a disabled state where I could delete the field. If a user added that to a more important environment, it would have disabled everything and been unable to fix from the CP.

*Edit*: This was in Craft 3

**Comment by page-8** [comment]
Yikes, that does sound nasty. I'll look into it when I get a chance

**Comment by jacobgraf** [comment]
Found this extension and was super excited to use it. Installed it, set up my first Many to Many field using the docs and now my whole Craft install is borked with the error below. Is there any way to get it back up and running without having to rebuild my database? 😢

`Class 'Craft\base\Field' not found`

**Comment by jacobgraf** [comment]
I used Composer to remove the package and was able to get into the CP to delete the field, but yikes.

**Comment by engram-design** [comment]
This should be fixed in the latest versions of Craft which has better handling for missing plugins and missing fields.
