### ISSUE TITLE
Feature request: customize "Add an entry" text

### ISSUE THREAD

**Issue by KatieMFritz** [verbb/many-to-many#25]
With a normal Entry field, you can customize the "Add an entry" text. It would be great to do that with Many to Many fields as well. 

For example, here I would like to change the text to say "Add a room".
![screen shot 2019-03-05 at 11 10 57 am](https://user-images.githubusercontent.com/7085184/53797912-74646b00-3f37-11e9-9d6e-2b42bf010b56.png)

**Comment by engram-design** [comment]
Added in [2.0.0](https://github.com/verbb/many-to-many/releases/tag/2.0.0)
